name: "🐛 Rapport de Bug"
description: Signalez un dysfonctionnement du système Sovereign.
title: "[BUG] Description courte du problème"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de signaler ce bug ! Veuillez fournir autant de détails que possible.
  - type: textarea
    id: description
    attributes:
      label: Description du Bug
      description: Une description claire et concise de ce qui ne va pas.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour Reproduire
      description: Comment pouvons-nous reproduire ce comportement ?
      placeholder: |
        1. Lancez 'bun start'
        2. Tapez '...'
        3. Voyez l'erreur '...'
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: OS, version de Bun, modèle utilisé (llama4:8b, etc.)
  - type: textarea
    id: logs
    attributes:
      label: Logs d'Audit (Sentinel)
      description: Copiez ici les logs pertinents de ~/.amf-os/audit.json si possible.
